name: cot-faithfulness
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - pytorch-cuda=11.8
  - cudatoolkit
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - scikit-learn>=1.3.0
  - jupyter
  - ipywidgets
  - tqdm
  - pip
  - pip:
    - transformers>=4.30.0
    - transformer-lens>=1.17.0
    - einops>=0.7.0
    - plotly>=5.15.0
    - dash>=2.11.0
    - wandb>=0.15.0
    - datasets>=2.13.0
    - accelerate>=0.20.0
    - safetensors>=0.3.0
    - typing-extensions>=4.5.0
    - sae-lens>=1.0.0
    - pytest>=7.0.0
    - black>=23.0.0
    - flake8>=6.0.0
    - mypy>=1.0.0
    - pre-commit>=3.0.0
    - nbformat>=5.9.0
    - nbconvert>=7.6.0
    - ipykernel>=6.24.0
